### ISSUE TITLE
saw-remote-api server rerunning scripts

### ISSUE THREAD

**Issue by pnwamk** [GaloisInc/saw-script#1055]
Running the same python script (e.g., [salsa20.py](https://github.com/GaloisInc/saw-script/blob/master/saw-remote-api/test-scripts/salsa20.py)) against a persistent `saw-remote-api` server produces errors about registering names multiple times, e.g.:

```
$ python3 salsa20.py
Starting server
Loading Cryptol spec
Traceback (most recent call last):
  File "/Users/andrew/Repos/temp/saw-script-head/saw-remote-api/test-scripts/salsa20.py", line 19, in <module>
    c.cryptol_load_file(cryname).result()
  File "/Users/andrew/Repos/temp/saw-script-head/deps/argo/python/argo/interaction.py", line 163, in result
    return self.process_result(self._result_and_state_and_out_err()[0])
  File "/Users/andrew/Repos/temp/saw-script-head/deps/argo/python/argo/interaction.py", line 148, in _result_and_state_and_out_err
    raise self.process_error(exception)
saw.exceptions.CryptolError: error: Attempted to register the following name twice: cryptol:/Salsa20/quarterround
```

Commenting out the load lines for subsequent runs of the script does not resolve the issue (other problems arise).

This should probably Just Work(TM) without any modifications to any script (e.g., if we're asking the server to load a module that's already loaded, it should be a noop rather than an error).

First reported https://github.com/GaloisInc/saw-script/issues/1051#issuecomment-770913840 - reproducible on HEAD (50e325f1c5f82fbe28528537affbe9f1dc7a0535).

**Comment by pnwamk** [comment]
Moved https://github.com/GaloisInc/galois-py-toolkit/issues/5
